# Generated by Django 3.2.9 on 2021-11-14 17:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('username', models.CharField(blank=True, editable=False, max_length=150)),
                ('full_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('email', models.EmailField(blank=True, editable=False, max_length=255)),
                ('role', models.CharField(blank=True, editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
            ],
        ),
    ]
