# Generated by Django 3.2.9 on 2021-11-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('developer', 'Developer')], default='developer', max_length=32),
        ),
    ]
